### ISSUE TITLE
backlog: reorder writes

### ISSUE THREAD

**Issue by lispc** [scroll-tech/mpt-circuit#3]
(low priority)

https://github.com/privacy-scaling-explorations/zkevm-specs/pull/200#issuecomment-1144667560

we may need to consider all the writes need to be reordered in the circuit, to make connecting circuit together easier.

**Comment by lispc** [comment]
other approaches https://github.com/privacy-scaling-explorations/zkevm-specs/issues/217#issue-1258267969

**Comment by noel2004** [comment]
The ordering has been determinded by the generated witness so it is an external task for this project.

Now resolved in [zkgeth](https://github.com/scroll-tech/go-ethereum/pull/123)
